# Generated by Django 5.2.1 on 2025-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
    ]
